[workload.f1]
src = "./target/wasm32-wasip2/release/example-f1.wasm"

[workload.f1.instances]
min = 1
max = 10

[workload.f1.linux.cgroup]
type = "none"

# type = "host"
# path = "/path/to/cgroup"

# type = "dynamic"
# TODO: set CPU limits

[workload.f1.linux.namespace]
#ipc = "/path/to/ipcns"
#network = "/path/to/netns"
#uts = "/path/to/utsns"

[workload.f1.filesystem.mounts."/"]
type = "host"
path = "/tmp/fs"
mode = "ro"

[workload.f1.filesystem.mounts."/foo"]
type = "host"
path = "/tmp/foo"
mode = "rw"

[workload.f1.network.tcp.ipv4]
#type = "none" # default, no outside-world facing interfaces
type = "host"   # run in host namespace
address = "10.0.0.1" # 0.0.0.0 binds to 10.0.0.1, no other address is allowed to be bound

[workload.f1.network.tcp.ipv6]
#type = "none" # default, no outside-world facing interfaces
type = "host"   # run in host namespace
address = "::2"

[workload.f1.network.udp.ipv4]
#type = "none" # default, no outside-world facing interfaces
type = "host"   # run in host namespace
address = "10.0.0.2"

[workload.f1.network.udp.ipv6]
#type = "none" # default, no outside-world facing interfaces
type = "host"   # run in host namespace
address = "::3"

[workload.f1.network.dns]
#type = "none" # default, no DNS
type = "host"

[workload.f1.imports.default]
type = "wrpc"
transport = "nats"
prefix = "foo.bar.baz"

[workload.f1.imports."myorg:mypkg"]
type = "workload"
id = "f2"

[workload.f2]
src = "./target/wasm32-wasip2/release/example-f2.wasm"
