package wasmlet-examples:rust-f2;

world component {
    include wasmlet-examples:hello/server;
    include wasmlet-examples:redis/client;

    import wasmlet-examples:redis/resp3;
    import wasmlet-examples:redis/pool;
}
